### ISSUE TITLE
Change Meetings and Forum section in DG

### ISSUE THREAD

**Issue by theeugenechong** [AY2122S1-CS2113T-W13-4/tp#133]
@fansxx and @Rrraaaeee this is the feedback from this week's DG Review activity.
![image](https://user-images.githubusercontent.com/69380888/139520558-34723e1b-2458-4f1c-a9ed-5123d0f6e1ab.png)

I went and checked some DG samples and realised that the `Meetings` and `Forum` sections should be under the `Resources` section and under 'Design'. Same goes for `Finance`

For `Implementation` it's more of like what happens and how each feature is implemented, so for e.g. we need to include a section like 'Scheduling a meeting' then include sequence diagrams + explanation to show what happens exactly.

**Comment by Rrraaaeee** [comment]
Right, that makes sense. So we should separate the class description and the software implementations

**Comment by theeugenechong** [comment]
Yep! 👍
