### ISSUE TITLE
[PE-D] Somewhat serious UI/Visual bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#147]
When adding posts, the UI that outputs successful post created is quite jarring and is different from the expected output as mentioned on the UG:

![image.png](https://raw.githubusercontent.com/adricpjw/ped/main/files/6f93f164-03d5-474b-98ec-78ba583c6014.png)

Actual Output:

![image.png](https://raw.githubusercontent.com/adricpjw/ped/main/files/49567a8f-6c3c-4ab6-8fb0-b165f6048aaf.png)

This might be due to differing encoding during compilation

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: adricpjw/ped#2

**Comment by theeugenechong** [comment]
Similar to #154
