### ISSUE TITLE
[PE-D] Incorrect error message for a correct format input for post list [postId]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#157]
![error 5.PNG](https://raw.githubusercontent.com/theodorekwok/ped/main/files/86a3df00-f1f9-4a5a-9874-147c136bdb2a.PNG)

The format followed (post list [postId]) is correct but it tells me to enter a number.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodorekwok/ped#5

**Comment by theeugenechong** [comment]
Update the exception thrown at parser

**Comment by Rrraaaeee** [comment]
The new error message is updated to `Please enter a valid number (0 to 99999999) for the argument!`
