### ISSUE TITLE
[PE-D] Error in accepting available command with extraneous parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#160]
![error 6.PNG](https://raw.githubusercontent.com/theodorekwok/ped/main/files/09641452-7aed-48d0-aa7a-5fbba6f8f890.PNG)

The user guide does not state what happens when extraneous parameters are entered.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: theodorekwok/ped#6

**Comment by theeugenechong** [comment]
Update UG in general
