### ISSUE TITLE
[PE-D] Balance sheet does not allow for decimal

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#161]
Balance sheets are meant to help manage finances and so precision is required.
Current implementation does not allow for decimals (must be whole number). This is impractical for most use cases where the numbers would likely have floating points.

Reproducible example:

![image.png](https://raw.githubusercontent.com/adricpjw/ped/main/files/d9cbe458-a998-4144-80ec-93563a49743a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: adricpjw/ped#5

**Comment by theeugenechong** [comment]
Similar to #178
