### ISSUE TITLE
[PE-D] Very large numbers are not handled properly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#163]
**Steps to reproduce**

1. As admin, enter `bs` (or `cf`)
2. `add 3898923423` (or some very large number)

**Expected**

Expected this big number to go through as it is not stated anywhere in the UG that there is a limit.

**Actual**

Got an error message "Please enter a number", which is quite misleading as I did enter a number :( 

![image.png](https://raw.githubusercontent.com/tlyi/ped/main/files/2dd41447-89f8-4077-9b99-844da4963039.png)

Consider handling int overflow messages differently, if possible!

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tlyi/ped#5

**Comment by theeugenechong** [comment]
Similar to #181
