### ISSUE TITLE
[PE-D] Lack of error handling in input "years" for proj command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#167]
**Steps to reproduce**

1. As admin enter `proj -1`

**Expected**

Expected an error message since you cannot project backwards in time..

**Actual**

I was given 0 year projection instead. 

![image.png](https://raw.githubusercontent.com/tlyi/ped/main/files/4e726de6-a3c7-4644-adb0-de0b180eaa3c.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: tlyi/ped#6

**Comment by theeugenechong** [comment]
Throw exception if years is <= 0
