### ISSUE TITLE
[PE-D] UG `meetings` and `schedule` command could be placed together. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#170]
In the user guide, there is a section about halfway through the UG that covers the `meetings` command. 
The `schedule` command, which is the only way to add a meeting, is all the way at the bottom of the UG. 

This seems confusing to me as readers might miss out the schedule command and wonder why there is a need to list meetings when there is no way to add one (to their knowledge).

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: titustortoiseturtle1999/ped#5

**Comment by theeugenechong** [comment]
Add hyperlink between schedule and meetings section
