### ISSUE TITLE
[PE-D] Limitation of username and password 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#173]
There is no way to register a user with username `pw` and password `pw`. 
The error message does not give any indication that this is a limitation of the program as well, but just throws a regular incorrect format error. 
![image.png](https://raw.githubusercontent.com/titustortoiseturtle1999/ped/main/files/a0bdfc64-c5c1-4831-9fc6-a5e781b9e61e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: titustortoiseturtle1999/ped#6

**Comment by theeugenechong** [comment]
Similar to #179

**Comment by Rrraaaeee** [comment]
New format will be ` register pw /pw pw /as admin`. Reserved words will be led by `/`
