### ISSUE TITLE
[PE-D] Income should allow cents

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W13-4/tp#178]
![error 13.PNG](https://raw.githubusercontent.com/theodorekwok/ped/main/files/92b546ba-1c53-40ba-857b-18444e826d5d.PNG)

The net income should allow me to add a double, as dollars

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: theodorekwok/ped#13

**Comment by theeugenechong** [comment]
similar to #181
