### ISSUE TITLE
Cannot use "help" command during sign-in

### ISSUE THREAD

**Issue by Rrraaaeee** [AY2122S1-CS2113T-W13-4/tp#185]
<img width="513" alt="Screenshot 2021-10-31 at 3 06 12 PM" src="https://user-images.githubusercontent.com/39750323/139572295-22d92ef1-bd6b-4468-9757-9d0f31c25399.png">
Maybe change the prompt message?

**Comment by theeugenechong** [comment]
Okay! I'll just update it to print something like "You are at at the sign-in section" +  the bottom two lines
